
import {
  Wallet01Icon,
  BankIcon,
  CreditCardIcon,
  PiggyBankIcon,
  Agreement02Icon,
  Airplane01Icon,
  Airpod03Icon,
  AlmsIcon,
  AmazonIcon,
  ApartmentIcon,
  MusicNoteSquare01Icon,
  ChampionIcon,
  BabyBoyDressIcon,
  Basketball02Icon,
  Backpack03Icon,
  BodyPartMuscleIcon,
  Book02Icon,
  Briefcase01Icon,
  BubbleTea02Icon,
  CafeIcon,
  BulbChargingIcon,
  Camera03Icon,
  Car02Icon,
  ChefHatIcon,
  Coffee02Icon,
  DentalToothIcon,
  FlimSlateIcon,
  HandBag01Icon,
  Hamburger02Icon,
  Home07Icon,
  IceCream03Icon,
  Money03Icon,
  LaptopIcon,
  MapsLocation02Icon,
  Mortarboard02Icon,
  PackageIcon,
  Pizza01Icon,
  Plant01Icon,
  RepairIcon,
  SpoonAndKnifeIcon,
  ShoppingBag02Icon,
  ShoppingCart02Icon,
  SmartPhone02Icon,
  SmartWatch01Icon,
  Sofa03Icon,
  SquareLock01Icon,
  StarIcon,
  Store02Icon,
  TemperatureIcon,
  TipsIcon,
  UserMultiple02Icon,
  Brain03Icon,
  BedDoubleIcon,
  FishFoodIcon,
  ChartCandleIcon
} from "@hugeicons/core-free-icons";

export const ICON_OPTIONS = [
  { name: "wallet", value: "wallet", icon: Wallet01Icon },
  { name: "bank", value: "bank", icon: BankIcon },
  { name: "card", value: "card", icon: CreditCardIcon },
  { name: "cash", value: "cash", icon: Money03Icon },
  { name: "piggy", value: "piggy", icon: PiggyBankIcon },
  { name: "aggrement", value: "agreement", icon: Agreement02Icon },
  { name: "airplane", value: "airplane", icon: Airplane01Icon },
  { name: "airpod", value: "airpod", icon: Airpod03Icon },
  { name: "alms", value: "alms", icon: AlmsIcon },
  { name: "amazon", value: "amazon", icon: AmazonIcon },
  { name: "apartment", value: "apartment", icon: ApartmentIcon },
  { name: "music", value: "music", icon: MusicNoteSquare01Icon },
  { name: "award", value: "award", icon: ChampionIcon },
  { name: "babyboy", value: "babyboy", icon: BabyBoyDressIcon },
  { name: "basket", value: "basket", icon: Basketball02Icon },
  { name: "backpack", value: "backpack", icon: Backpack03Icon },
  { name: "bodypart", value: "bodypart", icon: BodyPartMuscleIcon },
  { name: "book", value: "book", icon: Book02Icon },
  { name: "briefcase", value: "briefcase", icon: Briefcase01Icon },
  { name: "bubble-tea", value: "bubble-tea", icon: BubbleTea02Icon },
  { name: "cafe", value: "cafe", icon: CafeIcon },
  { name: "bulb-charging", value: "bulb-charging", icon: BulbChargingIcon },
  { name: "camera", value: "camera", icon: Camera03Icon },
  { name: "car", value: "car", icon: Car02Icon },
  { name: "chef", value: "chef", icon: ChefHatIcon },
  { name: "coffee", value: "coffee", icon: Coffee02Icon },
  { name: "dental", value: "dental", icon: DentalToothIcon },
  { name: "film", value: "film", icon: FlimSlateIcon },
  { name: "handbag", value: "handbag", icon: HandBag01Icon },
  { name: "burger", value: "burger", icon: Hamburger02Icon },
  { name: "home", value: "home", icon: Home07Icon },
  { name: "ice-cream", value: "ice-cream", icon: IceCream03Icon },
  { name: "laptop", value: "laptop", icon: LaptopIcon },
  { name: "maps", value: "maps", icon: MapsLocation02Icon },
  { name: "mortar-board", value: "mortar-board", icon: Mortarboard02Icon },
  { name: "package", value: "package", icon: PackageIcon },
  { name: "pizza", value: "pizza", icon: Pizza01Icon },
  { name: "plant", value: "plant", icon: Plant01Icon },
  { name: "repair", value: "repair", icon: RepairIcon },
  { name: "restaurant", value: "restaurant", icon: SpoonAndKnifeIcon },
  { name: "shopping", value: "shopping", icon: ShoppingBag02Icon },
  { name: "cart", value: "cart", icon: ShoppingCart02Icon },
  { name: "phone", value: "phone", icon: SmartPhone02Icon },
  { name: "watch", value: "watch", icon: SmartWatch01Icon },
  { name: "sofa", value: "sofa", icon: Sofa03Icon },
  { name: "lock", value: "lock", icon: SquareLock01Icon },
  { name: "star", value: "star", icon: StarIcon },
  { name: "store", value: "store", icon: Store02Icon },
  { name: "temperature", value: "temperature", icon: TemperatureIcon },
  { name: "tips", value: "tips", icon: TipsIcon },
  { name: "users", value: "users", icon: UserMultiple02Icon },
  { name: "brain", value: "brain", icon: Brain03Icon },
  { name: "bed", value: "bed", icon: BedDoubleIcon },
  { name: "fish", value: "fish", icon: FishFoodIcon },
];

export const COLOR_OPTIONS = [
  { name: "default", value: "bg-foreground" },
  { name: "gray", value: "bg-gray" },
  { name: "brown", value: "bg-brown" },
  { name: "orange", value: "bg-orange" },
  { name: "yellow", value: "bg-yellow" },
  { name: "green", value: "bg-green" },
  { name: "blue", value: "bg-blue" },
  { name: "purple", value: "bg-purple" },
  { name: "pink", value: "bg-pink" },
  { name: "red", value: "bg-red-500" },
];

export const BG_COLOR: Record<string, string> = {
  default: "bg-foreground/20",
  gray: "bg-gray/20",
  brown: "bg-brown/20",
  orange: "bg-orange/20",
  yellow: "bg-yellow/20",
  green: "bg-green/20",
  blue: "bg-blue/20",
  purple: "bg-purple/20",
  pink: "bg-pink/20",
  red: "bg-red-500/20",
}

export const TEXT_COLOR: Record<string, string> = {
  default: "text-foreground",
  gray: "text-gray",
  brown: "text-brown",
  orange: "text-orange",
  yellow: "text-yellow",
  green: "text-green",
  blue: "text-blue",
  purple: "text-purple",
  pink: "text-pink",
  red: "text-red-500",
}

export const ACCOUNT_TYPES = [
  { label: "Bank Account", value: "bank", icon: BankIcon },
  { label: "Cash", value: "cash", icon: Money03Icon },
  { label: "E-Wallet", value: "e-wallet", icon: Wallet01Icon },
  { label: "Credit Card", value: "credit-card", icon: CreditCardIcon },
  { label: "Investment", value: "investment", icon: ChartCandleIcon }
]
